import {
  barChart,
  donutChart,
  distributionChart,
  riskMatrix,
  timelineChart,
  escapeXml,
  CHART_ACCENT,
  CHART_BAD,
  CHART_GRID,
  CHART_MUTED,
  CHART_OK,
  CHART_WARN,
  type TimelineItem,
} from "./reportCharts";
import { isIncidentClosed } from "./conformityEngine";
import { CitationRegistry } from "./reportCitations";
import {
  STATUS_LABELS,
  RISK_ORDER,
  audienceLabel,
  formatLabel,
  type AssessmentSnapshot,
  type PortfolioSnapshot,
  type ReportAudience,
  type ReportFormat,
  type SnapshotRequirement,
} from "./reportTypes";
import type { ReportOptions } from "@workspace/db";

/**
 * Deterministic section renderers. Pure functions from a frozen snapshot to
 * HTML strings — no I/O, no randomness, so a report's deterministic sections
 * are reproducible byte-for-byte from its stored snapshot.
 */

export const esc = escapeXml; // HTML-safe for our subset (no attribute quirks used)

export class Figures {
  private n = 0;
  caption(text: string): string {
    this.n += 1;
    return `<figcaption>Figure ${this.n}. ${esc(text)}</figcaption>`;
  }
}

function badge(status: string): string {
  const cls =
    status === "met" ? "ok" : status === "partial" || status === "in_progress" ? "warn" : status === "not_met" ? "bad" : "na";
  return `<span class="badge ${cls}">${esc(STATUS_LABELS[status] ?? status)}</span>`;
}

function riskBadge(risk: string | null): string {
  if (!risk) return '<span class="muted">—</span>';
  const cls = risk === "critical" || risk === "high" ? "bad" : risk === "medium" ? "warn" : "na";
  return `<span class="badge ${cls}">${esc(risk)}</span>`;
}

const dateFmt = (iso: string | null | undefined): string => (iso ? iso.slice(0, 10) : "—");

function daysUntil(iso: string, from: string): number {
  return Math.ceil((new Date(iso).getTime() - new Date(from).getTime()) / 86_400_000);
}

// ---------------------------------------------------------------------------
// Assessment-scope sections
// ---------------------------------------------------------------------------

export function renderAssessmentCover(
  s: AssessmentSnapshot,
  format: ReportFormat,
  audience: ReportAudience,
  title: string,
): string {
  const distribution =
    audience === "board"
      ? "Confidential — prepared for the board of directors"
      : "Prepared for regulatory review and market-surveillance readiness";
  const meta: [string, string][] = [
    ["Product", `${s.product.name}${s.product.version ? ` (v${s.product.version})` : ""}`],
    ["Manufacturer", s.product.manufacturerName || "—"],
    ["Regulation", s.regulations[0]?.shortName ?? s.assessment.regulationKey.toUpperCase()],
    ["Assessment reference", `CONF-${s.assessment.id}`],
    ["Classification", s.assessment.className ?? "Not yet classified"],
    ["Conformity route", s.assessment.routeName ?? "Not yet selected"],
    ["Overall grade", `${s.grade.overallGrade} (${s.grade.overallScore}/100)`],
    ["Report date", dateFmt(s.generatedAt)],
    ["Edition", audienceLabel(audience)],
  ];
  return `<div class="cover">
<div>
  <div class="brand">OXOT · CONFORMITY</div>
  <h1 style="margin-top:18px">${esc(title)}</h1>
  <div class="subtitle">${esc(formatLabel(format))} · EU Cyber Resilience Act</div>
</div>
<div class="coverline">
  <table>${meta.map(([k, v]) => `<tr><td style="width:34%" class="muted">${esc(k)}</td><td><strong>${esc(v)}</strong></td></tr>`).join("")}</table>
  <p class="doc-meta" style="margin-top:10px">${esc(distribution)}. Generated by the OXOT Conformity Workbench from the assessment's evidence-backed working record; all figures, tables and citations are computed deterministically from a snapshot frozen at generation time.</p>
</div>
</div>`;
}

export function renderDocumentControl(s: AssessmentSnapshot, audience: ReportAudience): string {
  return `<table>
<tr><th style="width:34%">Item</th><th>Value</th></tr>
<tr><td>Document status</td><td>Working draft until finalised in the workbench</td></tr>
<tr><td>Prepared by</td><td>OXOT Conformity Workbench (automated compilation, analyst-reviewed)</td></tr>
<tr><td>Distribution</td><td>${audience === "board" ? "Board of directors; senior compliance leadership" : "Competent market-surveillance authority; notified body (where engaged)"}</td></tr>
<tr><td>Data snapshot</td><td>${esc(dateFmt(s.generatedAt))} — assessment CONF-${s.assessment.id}, last updated ${esc(dateFmt(s.assessment.updatedAt))}</td></tr>
<tr><td>Method</td><td>See Methodology; grading weights 70% requirements / 30% documentation</td></tr>
</table>`;
}

export function renderKpiBand(s: AssessmentSnapshot): string {
  const nearest = s.deadlines.filter((d) => !d.done);
  const nearestText = nearest.length
    ? `${daysUntil(nearest[0]!.dueAt, s.generatedAt)}d`
    : "—";
  const nearestLabel = nearest.length ? nearest[0]!.label : "No statutory deadline pending";
  const openIncidentCount = s.incidents.filter((i) => !isIncidentClosed(i.status)).length;

  const kpis: { val: string; label: string; sub: string; tone?: string }[] = [
    {
      val: s.grade.overallGrade,
      label: "Overall Grade",
      sub: `Score: ${s.grade.overallScore}/100`,
      tone: s.grade.overallGrade === "A" || s.grade.overallGrade === "B" ? "ok" : "bad",
    },
    {
      val: `${s.grade.overallScore}`,
      label: "Compliance Score",
      sub: "Out of 100 max",
      tone: s.grade.overallScore >= 80 ? "ok" : s.grade.overallScore >= 60 ? "warn" : "bad",
    },
    {
      val: `${s.readiness.percent}%`,
      label: "Requirements Met",
      sub: `${s.readiness.met} of ${s.readiness.total - s.readiness.notApplicable} applicable`,
      tone: s.readiness.percent >= 80 ? "ok" : "warn",
    },
    {
      val: `${s.grade.blockerCount}`,
      label: "Critical Blockers",
      sub: "Action items capping grade",
      tone: s.grade.blockerCount > 0 ? "bad" : "ok",
    },
    {
      val: `${openIncidentCount}`,
      label: "Open Incidents",
      sub: "Article 14 CSIRT tracks",
      tone: openIncidentCount > 0 ? "warn" : "ok",
    },
    {
      val: nearestText,
      label: "Nearest SLA Clock",
      sub: nearestLabel,
      tone: nearestText.includes("d") ? "warn" : "muted",
    },
  ];

  return `<div class="kpi-grid">${kpis
    .map(
      (k) =>
        `<div class="kpi-card ${k.tone ? `kpi-${k.tone}` : ""}"><div class="kpi-label">${esc(k.label)}</div><div class="kpi-val">${esc(k.val)}</div><div class="kpi-sub">${esc(k.sub)}</div></div>`,
    )
    .join("")}</div>`;
}

export function renderPostureCharts(s: AssessmentSnapshot, figures: Figures): string {
  const donut = donutChart({
    segments: [
      { label: "Met", value: s.readiness.met, color: CHART_OK },
      { label: "Partially met", value: s.readiness.partial, color: CHART_WARN },
      { label: "Open", value: s.readiness.open, color: CHART_BAD },
      { label: "Not applicable", value: s.readiness.notApplicable, color: CHART_GRID },
    ],
    centerLabel: `${s.readiness.percent}%`,
    centerSub: "requirements met",
  });
  const bars = barChart({
    bars: s.themes
      .filter((t) => t.total > 0)
      .map((t) => ({
        label: t.name,
        value: t.score,
        max: 100,
        color: t.score >= 80 ? CHART_OK : t.score >= 50 ? CHART_WARN : CHART_BAD,
      })),
    valueSuffix: "%",
  });
  return `<div class="figure-row">
<figure>${donut}${figures.caption("Evaluation status across all applicable essential requirements.")}</figure>
<figure>${bars}${figures.caption("Coverage score by obligation theme (grading model, 0–100).")}</figure>
</div>`;
}

export function renderClassificationRoute(s: AssessmentSnapshot, reg: CitationRegistry): string {
  const cra = reg.cite("reg:" + s.assessment.regulationKey) || reg.cite("bib:cra");
  const scopeLine =
    s.assessment.scopeResult === "out_of_scope"
      ? `<p>The scoping review concluded that the product is <strong>outside the scope</strong> of the regulation ${cra}; the remainder of this report records the analysis supporting that conclusion.</p>`
      : `<p>The scoping review concluded that the product is <strong>within scope</strong> of the regulation as a product with digital elements ${cra}.</p>`;
  const cls = s.assessment.className
    ? `<p>The product is classified as <strong>${esc(s.assessment.className)}</strong>. The selected conformity assessment route is <strong>${esc(s.assessment.routeName ?? s.assessment.routeKey ?? "not yet selected")}</strong>. The classification and route recorded here are those the eventual EU declaration of conformity would assert.</p>`
    : `<p>Classification has not yet been recorded; route selection and the resulting obligations remain provisional.</p>`;
  const advisory = s.standardsAdvisory
    ? `<div class="callout"><strong>Route validity advisory.</strong> ${esc(s.standardsAdvisory)}</div>`
    : "";
  return scopeLine + cls + advisory;
}

export function renderFindingsOverview(s: AssessmentSnapshot, figures: Figures): string {
  const rows = s.themes
    .filter((t) => t.total > 0)
    .map(
      (t) =>
        `<tr><td>${esc(t.name)}</td><td>${t.met}</td><td>${t.partial}</td><td>${t.open}</td><td>${t.notApplicable}</td><td><strong>${t.score}%</strong></td></tr>`,
    )
    .join("");
  return `${renderPostureCharts(s, figures)}
<table>
<tr><th>Obligation theme</th><th>Met</th><th>Partial</th><th>Open</th><th>N/A</th><th>Coverage</th></tr>
${rows}
</table>`;
}

const MATRIX_STATUSES = ["not_met", "partial", "in_progress", "not_started"] as const;
const MATRIX_RISKS = ["critical", "high", "medium", "low"] as const;

export function renderRiskAnalysis(s: AssessmentSnapshot, figures: Figures): string {
  const cells: number[][] = MATRIX_RISKS.map((risk) =>
    MATRIX_STATUSES.map(
      (status) => s.gaps.filter((g) => (g.riskRating ?? "medium") === risk && g.status === status).length,
    ),
  );
  const matrix = riskMatrix({
    rows: cells,
    rowLabels: ["Critical", "High", "Medium", "Low"],
    colLabels: ["Not met", "Partially met", "In progress", "Not started"],
  });
  const register = s.gaps
    .slice(0, 14)
    .map(
      (g) =>
        `<tr><td>${esc(g.refCode)}</td><td>${esc(g.title)}</td><td>${riskBadge(g.riskRating)}</td><td>${badge(g.status)}</td><td>${esc(g.owner || "—")}</td><td>${dateFmt(g.dueDate)}</td></tr>`,
    )
    .join("");
  return `<figure>${matrix}${figures.caption("Open requirement exposure: recorded risk rating × evaluation status (counts).")}</figure>
<table>
<tr><th>Ref</th><th>Requirement</th><th>Risk</th><th>Status</th><th>Owner</th><th>Due</th></tr>
${register || '<tr><td colspan="6" class="muted">No open requirements — the risk register is clear.</td></tr>'}
</table>`;
}

export function renderStandardsSection(s: AssessmentSnapshot, reg: CitationRegistry): string {
  const cra = reg.cite("reg:" + s.assessment.regulationKey) || reg.cite("bib:cra");
  const enisa = reg.cite("bib:enisa-standards");
  const rows = s.appliedStandards
    .map((std) => {
      const cite = reg.cite(`std:${std.reference}`);
      return `<tr><td><strong>${esc(std.reference)}</strong> ${cite}</td><td>${esc(std.title ?? "—")}</td><td>${std.coverage === "full" ? '<span class="badge ok">Applied in full</span>' : '<span class="badge warn">Applied in part</span>'}</td><td>${esc(std.notes ?? "")}</td></tr>`;
    })
    .join("");
  const intro = rows
    ? `<p>The manufacturer records the following harmonised standards and technical specifications as applied to the product. Where a harmonised standard whose reference has been published in the Official Journal is applied <em>in full</em>, conformity with the essential requirements it covers is presumed ${cra}; partial application confers no presumption and the corresponding requirements must be evidenced directly ${enisa}.</p>
<table><tr><th>Reference</th><th>Title</th><th>Coverage</th><th>Notes</th></tr>${rows}</table>`
    : `<p>No harmonised standards or technical specifications have been recorded against this assessment. Conformity with each essential requirement must therefore be demonstrated directly through the technical documentation, without presumption of conformity ${cra}.</p>`;
  const advisory = s.standardsAdvisory
    ? `<div class="callout"><strong>Route validity advisory.</strong> ${esc(s.standardsAdvisory)}</div>`
    : "";
  return intro + advisory;
}

export function renderIncidents(s: AssessmentSnapshot, options: ReportOptions, figures: Figures): string {
  if (s.incidents.length === 0) {
    return `<p>No reportable incidents or actively exploited vulnerabilities are recorded against this product. The Article 14 reporting apparatus (24-hour early warning, 72-hour notification, final report) is nonetheless a live obligation from the moment of awareness; readiness is assessed under the remediation programme.</p>`;
  }
  const rows = s.incidents
    .map((i) => {
      const clockCell = (idx: number): string => {
        const c = i.clocks[idx];
        if (!c) return "<td>—</td>";
        if (c.doneAt) return `<td><span class="badge ok">Done ${dateFmt(c.doneAt)}</span></td>`;
        return `<td><span class="badge ${c.overdue ? "bad" : "warn"}">${c.overdue ? "Overdue" : "Due"} ${dateFmt(c.dueAt)}</span></td>`;
      };
      return `<tr><td>${esc(i.title)}</td><td>${esc(i.kind === "exploited_vulnerability" ? "Exploited vulnerability (Art 14(1))" : "Severe incident (Art 14(3))")}</td><td>${riskBadge(i.severity)}</td><td>${dateFmt(i.detectedAt)}</td>${clockCell(0)}${clockCell(1)}${clockCell(2)}<td>${badge(isIncidentClosed(i.status) ? "met" : "in_progress")}</td></tr>`;
    })
    .join("");
  const timelineItems: TimelineItem[] = s.deadlines
    .filter((d) => d.kind === "statutory")
    .slice(0, 6)
    .map((d) => ({ label: d.label.length > 34 ? d.label.slice(0, 33) + "…" : d.label, date: new Date(d.dueAt), kind: d.done ? "done" : "due" }));
  const timeline =
    timelineItems.length > 0
      ? `<figure>${timelineChart({
          items: timelineItems,
          start: new Date(new Date(s.generatedAt).getTime() - 14 * 86_400_000),
          end: new Date(new Date(s.generatedAt).getTime() + 45 * 86_400_000),
        })}${figures.caption("Article 14 reporting clocks around the snapshot date.")}</figure>`
      : "";
  const detail = options.includeIncidentDetail
    ? s.incidents
        .map(
          (i) => `<h3>${esc(i.title)}</h3>
<table>
<tr><td style="width:34%" class="muted">Member states affected</td><td>${esc(i.memberStates || "Not yet recorded")}</td></tr>
<tr><td class="muted">Corrective / mitigating measures</td><td>${esc(i.correctiveMeasures || "Not yet recorded")}</td></tr>
<tr><td class="muted">Mitigations available to users</td><td>${esc(i.userMitigations || "Not yet recorded")}</td></tr>
</table>`,
        )
        .join("")
    : "";
  return `<table>
<tr><th>Incident</th><th>Track</th><th>Severity</th><th>Detected</th><th>Early warning (24h)</th><th>Notification (72h)</th><th>Final report</th><th>Status</th></tr>
${rows}
</table>${timeline}${detail}`;
}

export function renderSupplyChain(s: AssessmentSnapshot, reg: CitationRegistry, figures: Figures): string {
  if (s.boms.length === 0) {
    return `<p>No bill of materials has been ingested for this product. Component-level transparency (SBOM) is required by Annex I Part II ${reg.cite("reg:" + s.assessment.regulationKey) || reg.cite("bib:cra")}; producing and maintaining one is tracked in the remediation programme.</p>`;
  }
  const rows = s.boms
    .map(
      (b) =>
        `<tr><td>${esc(b.name)}</td><td>${esc(b.bomType.toUpperCase())}</td><td>${b.componentCount}</td><td>${b.findingCount}</td></tr>`,
    )
    .join("");
  const sev = s.boms.reduce(
    (acc, b) => ({
      critical: acc.critical + b.findingsBySeverity.critical,
      high: acc.high + b.findingsBySeverity.high,
      medium: acc.medium + b.findingsBySeverity.medium,
      low: acc.low + b.findingsBySeverity.low,
      other: acc.other + b.findingsBySeverity.other,
    }),
    { critical: 0, high: 0, medium: 0, low: 0, other: 0 },
  );
  const chart = barChart({
    bars: [
      { label: "Critical", value: sev.critical, max: Math.max(1, sev.critical, sev.high, sev.medium, sev.low), color: CHART_BAD },
      { label: "High", value: sev.high, max: Math.max(1, sev.critical, sev.high, sev.medium, sev.low), color: CHART_WARN },
      { label: "Medium", value: sev.medium, max: Math.max(1, sev.critical, sev.high, sev.medium, sev.low), color: CHART_ACCENT },
      { label: "Low / info", value: sev.low + sev.other, max: Math.max(1, sev.critical, sev.high, sev.medium, sev.low + sev.other), color: CHART_MUTED },
    ],
    width: 460,
  });
  const gaps =
    s.upstreamNotificationGaps > 0
      ? `<div class="callout"><strong>${s.upstreamNotificationGaps} upstream maintainer notification(s) pending.</strong> Article 13(6) requires the manufacturer to report identified vulnerabilities in integrated components to their maintainers; the pending items are listed in the workbench BOM register.</div>`
      : "";
  return `<table><tr><th>Bill of materials</th><th>Type</th><th>Components</th><th>Findings</th></tr>${rows}</table>
<figure>${chart}${figures.caption("Open component findings by severity across all ingested BOMs.")}</figure>${gaps}`;
}

export function renderRemediation(s: AssessmentSnapshot): string {
  if (s.gaps.length === 0) {
    return `<p>All applicable requirements are evidenced as met; no remediation items remain. The programme focus shifts to sustainment: keeping evidence, documentation and vulnerability-handling processes current for the duration of the support period.</p>`;
  }
  const rows = s.gaps
    .slice(0, 20)
    .map(
      (g, i) =>
        `<tr><td>${i + 1}</td><td>${esc(g.refCode)}</td><td>${esc(g.title)}</td><td>${riskBadge(g.riskRating)}</td><td>${badge(g.status)}</td><td>${esc(g.owner || "Unassigned")}</td><td>${dateFmt(g.dueDate)}</td></tr>`,
    )
    .join("");
  return `<p>The remediation worklist below is ordered by recorded risk rating and due date; it is the deterministic input from which the recommendations in this report are drawn.</p>
<table>
<tr><th>#</th><th>Ref</th><th>Requirement</th><th>Risk</th><th>Status</th><th>Owner</th><th>Due</th></tr>
${rows}
</table>`;
}

export function renderMethodology(s: AssessmentSnapshot, reg: CitationRegistry): string {
  const cra = reg.cite("reg:" + s.assessment.regulationKey) || reg.cite("bib:cra");
  const blue = reg.cite("bib:blue-guide");
  const enisa = reg.cite("bib:enisa-standards");
  const nlf = reg.cite("bib:768-2008");
  return `<p>This report is compiled from the OXOT Conformity Workbench's working record for assessment CONF-${s.assessment.id}. The assessment method proceeds in five stages: scoping against the regulation's definition of a product with digital elements ${cra}; classification against the importance criteria of Annex III and selection of a conformity assessment route consistent with the New Legislative Framework ${nlf}${blue}; obligation mapping, in which the essential requirements of Annex I Parts I and II are decomposed into discrete, evaluable requirements; evaluation, in which each requirement is assessed as met, partially met, not met, not applicable, or not yet started, with an implementation note, an accountable owner, a risk rating and a due date; and documentation review across the technical file artefacts required for the chosen route.</p>
<p>Quantitative figures use the workbench grading model: the overall score weights requirement coverage at 70% and documentation completeness at 30%; a requirement evaluated as <em>not met</em> with a critical or high risk rating is a <em>blocker</em> irrespective of the aggregate score. Theme coverage scores are the grading model's per-theme results on a 0–100 scale. These conventions are held constant across reports, so scores are comparable over time and across products.</p>
<p>Evidence is registered with content hashes (SHA-256) and timestamps in an append-only activity ledger, providing a chain of custody from claim to artefact. Where harmonised standards are recorded as applied in full, the corresponding requirements benefit from a presumption of conformity ${cra}; the mapping between standards and requirements follows the published standardisation mapping ${enisa}.</p>
<p><strong>Limitations.</strong> Evaluations and evidence are self-declared by the manufacturer's assessment team and reviewed by OXOT; this report is a conformity-readiness analysis, not a notified-body certificate or a legal opinion. Figures reflect the data snapshot of ${dateFmt(s.generatedAt)} and do not incorporate later changes to the working record.</p>`;
}

export function renderRequirementMatrix(s: AssessmentSnapshot, includeNotes: boolean): string {
  const byTheme = new Map<string, SnapshotRequirement[]>();
  for (const r of s.requirements) {
    const list = byTheme.get(r.themeName) ?? [];
    list.push(r);
    byTheme.set(r.themeName, list);
  }
  const blocks: string[] = [];
  for (const [themeName, reqs] of byTheme) {
    const rows = reqs
      .map(
        (r) =>
          `<tr><td style="white-space:nowrap">${esc(r.refCode)}</td><td>${esc(r.title)}</td><td>${badge(r.status)}</td><td>${riskBadge(r.riskRating)}</td><td>${esc(r.owner || "—")}</td><td>${dateFmt(r.dueDate)}</td>${includeNotes ? `<td>${esc(r.note || "")}</td>` : ""}</tr>`,
      )
      .join("");
    blocks.push(`<h3>${esc(themeName)}</h3>
<table><tr><th>Ref</th><th>Requirement</th><th>Status</th><th>Risk</th><th>Owner</th><th>Due</th>${includeNotes ? "<th>Implementation note</th>" : ""}</tr>${rows}</table>`);
  }
  return blocks.join("");
}

export function renderEvidenceRegister(s: AssessmentSnapshot): string {
  if (s.evidence.length === 0) return `<p class="muted">No evidence items are registered.</p>`;
  const rows = s.evidence
    .map(
      (e) =>
        `<tr><td>E-${e.id}</td><td>${esc(e.title)}</td><td>${esc(e.evidenceType)}</td><td>${esc(e.requirementRefCode ?? "—")}</td><td>${esc(e.fileName || "—")}</td><td>${e.hashPrefix ? `<code>${esc(e.hashPrefix)}…</code>` : "—"}</td><td>${dateFmt(e.createdAt)}</td></tr>`,
    )
    .join("");
  return `<table><tr><th>Ref</th><th>Title</th><th>Type</th><th>Requirement</th><th>File</th><th>SHA-256</th><th>Registered</th></tr>${rows}</table>`;
}

export function renderActivityExtract(s: AssessmentSnapshot): string {
  if (s.activityTail.length === 0) return `<p class="muted">No ledger entries.</p>`;
  const rows = s.activityTail
    .map((a) => `<tr><td style="white-space:nowrap">${dateFmt(a.createdAt)}</td><td>${esc(a.summary)}</td><td>${esc(a.actor || "system")}</td></tr>`)
    .join("");
  return `<p>The most recent entries of the append-only activity ledger, demonstrating the chain of custody behind this report's figures.</p>
<table><tr><th>Date</th><th>Event</th><th>Actor</th></tr>${rows}</table>`;
}

export function renderReferences(reg: CitationRegistry): string {
  const items = reg.citations.map((c) => `<li value="${c.n}">${esc(c.label)}</li>`).join("");
  return `<div class="references"><ol>${items}</ol></div>`;
}

// ---------------------------------------------------------------------------
// Readout pages (assessment)
// ---------------------------------------------------------------------------

export function renderReadoutPosture(s: AssessmentSnapshot, figures: Figures): string {
  return `<div class="readout-page">${renderKpiBand(s)}${renderPostureCharts(s, figures)}</div>`;
}

export function renderReadoutDeadlines(s: AssessmentSnapshot, figures: Figures): string {
  const pending = s.deadlines.filter((d) => !d.done).slice(0, 8);
  if (pending.length === 0) return `<div class="readout-page"><p>No statutory or support-period deadlines pending.</p></div>`;
  const rows = pending
    .map((d) => `<tr><td>${esc(d.label)}</td><td>${dateFmt(d.dueAt)}</td><td>${daysUntil(d.dueAt, s.generatedAt)} days</td></tr>`)
    .join("");
  const items: TimelineItem[] = pending.slice(0, 6).map((d) => ({
    label: d.label.length > 30 ? d.label.slice(0, 29) + "…" : d.label,
    date: new Date(d.dueAt),
    kind: "due",
  }));
  return `<div class="readout-page">
<figure>${timelineChart({ items, start: new Date(s.generatedAt), end: new Date(new Date(s.generatedAt).getTime() + 90 * 86_400_000) })}${figures.caption("Deadlines in the next 90 days.")}</figure>
<table><tr><th>Deadline</th><th>Due</th><th>In</th></tr>${rows}</table>
</div>`;
}

// ---------------------------------------------------------------------------
// Portfolio-scope sections
// ---------------------------------------------------------------------------

export function renderPortfolioCover(s: PortfolioSnapshot, format: ReportFormat, audience: ReportAudience, title: string): string {
  const meta: [string, string][] = [
    ["Products under assessment", String(s.productCount)],
    ["Assessments", String(s.assessmentCount)],
    ["Average score", `${s.averageScore}/100`],
    ["Open blockers", String(s.totals.blockers)],
    ["Open incidents", String(s.totals.openIncidents)],
    ["Report date", dateFmt(s.generatedAt)],
    ["Edition", audienceLabel(audience)],
  ];
  return `<div class="cover">
<div>
  <div class="brand">OXOT · CONFORMITY</div>
  <h1 style="margin-top:18px">${esc(title)}</h1>
  <div class="subtitle">${esc(formatLabel(format))} · Portfolio edition · EU Cyber Resilience Act</div>
</div>
<div class="coverline">
  <table>${meta.map(([k, v]) => `<tr><td style="width:34%" class="muted">${esc(k)}</td><td><strong>${esc(v)}</strong></td></tr>`).join("")}</table>
  <p class="doc-meta" style="margin-top:10px">${audience === "board" ? "Confidential — prepared for the board of directors." : "Prepared for regulatory review."} Compiled deterministically from the workbench's live assessment records, frozen at generation time.</p>
</div>
</div>`;
}

export function renderPortfolioKpis(s: PortfolioSnapshot, figures: Figures): string {
  const kpis: [string, string][] = [
    [String(s.productCount), "Products"],
    [`${s.averageScore}`, "Avg score / 100"],
    [String(s.totals.blockers), "Open blockers"],
    [String(s.totals.openGaps), "Open gaps"],
    [String(s.totals.openIncidents), "Open incidents"],
    [String(s.totals.overdueDeadlines), "Overdue deadlines"],
  ];
  const chart = distributionChart({
    columns: s.gradeDistribution.map((g) => ({
      label: g.grade,
      value: g.count,
      color: g.grade === "A" || g.grade === "B" ? CHART_OK : g.grade === "C" ? CHART_WARN : CHART_BAD,
    })),
  });
  return `<div class="kpi-grid">${kpis.map(([v, l]) => `<div class="kpi"><div class="v">${esc(v)}</div><div class="l">${esc(l)}</div></div>`).join("")}</div>
<figure>${chart}${figures.caption("Grade distribution across the assessed portfolio.")}</figure>`;
}

export function renderPortfolioTable(s: PortfolioSnapshot): string {
  const rows = s.rows
    .map(
      (r) =>
        `<tr><td><strong>${esc(r.productName)}</strong>${r.version ? ` <span class="muted">v${esc(r.version)}</span>` : ""}</td><td>${esc(r.currentStage)}</td><td>${esc(r.grade)} (${r.score})</td><td>${r.blockers}</td><td>${r.openGaps}</td><td>${r.openIncidents}</td><td>${r.nearestDeadline ? `${esc(r.nearestDeadline.label)} — ${dateFmt(r.nearestDeadline.dueAt)}` : "—"}</td></tr>`,
    )
    .join("");
  return `<table>
<tr><th>Product</th><th>Stage</th><th>Grade</th><th>Blockers</th><th>Open gaps</th><th>Incidents</th><th>Nearest deadline</th></tr>
${rows || '<tr><td colspan="7" class="muted">No assessments recorded.</td></tr>'}
</table>`;
}

export function renderSystemicGaps(s: PortfolioSnapshot): string {
  if (s.systemicGaps.length === 0) return `<p>No requirement fails across multiple products; open items are product-specific.</p>`;
  const rows = s.systemicGaps
    .map(
      (g) =>
        `<tr><td>${esc(g.refCode)}</td><td>${esc(g.title)}</td><td>${esc(g.themeName)}</td><td><strong>${g.failCount}</strong></td><td class="muted">${esc(g.products.join(", "))}</td></tr>`,
    )
    .join("");
  return `<p>Requirements open in two or more assessments indicate systemic engineering or process gaps that are best remediated once, centrally, rather than per product.</p>
<table><tr><th>Ref</th><th>Requirement</th><th>Theme</th><th>Products affected</th><th>Which</th></tr>${rows}</table>`;
}

export function renderDeadlineHorizon(s: PortfolioSnapshot, figures: Figures): string {
  if (s.deadlineHorizon.length === 0) return `<p>No statutory or support-period deadlines fall within the next 90 days.</p>`;
  const items: TimelineItem[] = s.deadlineHorizon.slice(0, 8).map((d) => ({
    label: `${d.productName}: ${d.label}`.length > 34 ? `${d.productName}: ${d.label}`.slice(0, 33) + "…" : `${d.productName}: ${d.label}`,
    date: new Date(d.dueAt),
    kind: d.done ? "done" : "due",
  }));
  const rows = s.deadlineHorizon
    .map((d) => `<tr><td>${esc(d.productName)}</td><td>${esc(d.label)}</td><td>${dateFmt(d.dueAt)}</td><td>${d.done ? '<span class="badge ok">Done</span>' : '<span class="badge warn">Pending</span>'}</td></tr>`)
    .join("");
  return `<figure>${timelineChart({ items, start: new Date(s.generatedAt), end: new Date(new Date(s.generatedAt).getTime() + 90 * 86_400_000) })}${figures.caption("Portfolio deadline horizon — next 90 days.")}</figure>
<table><tr><th>Product</th><th>Deadline</th><th>Due</th><th>Status</th></tr>${rows}</table>`;
}

export function renderPortfolioMethodology(reg: CitationRegistry): string {
  const cra = reg.cite("bib:cra");
  const blue = reg.cite("bib:blue-guide");
  return `<p>Portfolio figures aggregate each product's assessment record under the workbench grading model (70% requirement coverage, 30% documentation completeness). Grades and scores are therefore comparable across products and over time. Classification and route selections follow the regulation's Annex III importance criteria and the New Legislative Framework conformity-assessment modules ${cra}${blue}. Systemic gaps are requirements open in two or more assessments. All figures derive from a data snapshot frozen at generation time.</p>`;
}
