import { Router, type IRouter } from "express";
import healthRouter from "./health";
import siteRouter from "./site";
import pagesRouter from "./pages";
import adminRouter from "./admin";
import adminTeamRouter from "./adminTeam";
import chatRouter from "./chat";
import adminLeadsRouter from "./adminLeads";
import storageRouter from "./storage";
import adminCmsRouter from "./adminCms";
import adminMediaRouter from "./adminMedia";
import adminSettingsRouter from "./adminSettings";
import adminWizardRouter from "./adminWizard";
import trackingRouter from "./tracking";
import alertsCronRouter from "./alertsCron";
import adminAffiliateRouter from "./adminAffiliate";
import adminSeoRouter from "./adminSeo";
import adminAnalyticsRouter from "./adminAnalytics";
import adminContentRouter from "./adminContent";
import newsletterRouter from "./newsletter";
import adminNewsletterRouter from "./adminNewsletter";
import adminSocialRouter from "./adminSocial";
import adminIntegrationsRouter from "./adminIntegrations";
import seoRouter from "./seo";
import conformityRouter from "./conformity";
import conformityAssessmentsRouter from "./conformityAssessments";
import conformityBomsRouter from "./conformityBoms";
import conformityFlowsRouter from "./conformityFlows";
import conformityAssistantRouter from "./conformityAssistant";
import conformityMeRouter from "./conformityMe";
import conformityReportsRouter from "./conformityReports";
import conformityPsirtRouter from "./conformityPsirt";
import { conformityIntelligenceRouter } from "./conformityIntelligence";
import { auditorRouter } from "./conformityAuditor";

import regulatoryNewsRouter from "./regulatoryNews";
import conformitySelfcheckRouter from "./conformitySelfcheck";
import { productPortfolioRouter } from "./productPortfolio";
import { partnerScopeRouter } from "./partnerScope";
import { ecosystemRouter } from "./ecosystemRoutes";
import { craWikiRouter } from "./craWikiRoutes";
import { harmonisedStandardsRouter } from "./harmonisedStandardsRoutes";
import { openSourceStewardRouter } from "./openSourceStewardRoutes";
import { importerArchiveRouter } from "./importerArchiveRoutes";
import orgProfileRouter from "./orgProfile";
import { podcastStudioRouter } from "./podcastStudio";
import { craFaqRouter } from "./craFaqRoutes";

const router: IRouter = Router();

router.use(craFaqRouter);
router.use(podcastStudioRouter);
router.use("/portfolio", productPortfolioRouter);
router.use("/ecosystem", ecosystemRouter);
router.use("/wiki/cra", craWikiRouter);
router.use("/standards", harmonisedStandardsRouter);
router.use("/steward", openSourceStewardRouter);
router.use("/archive", importerArchiveRouter);
router.use(partnerScopeRouter);
router.use(regulatoryNewsRouter);
router.use(conformitySelfcheckRouter);
router.use(healthRouter);
router.use(seoRouter);
router.use(siteRouter);
router.use(conformityRouter);
router.use(conformityAssessmentsRouter);
router.use(conformityBomsRouter);
router.use(conformityFlowsRouter);
router.use(conformityAssistantRouter);
router.use(conformityMeRouter);
router.use(orgProfileRouter);
router.use(conformityReportsRouter);
router.use(conformityPsirtRouter);
router.use(conformityIntelligenceRouter);
router.use(auditorRouter);
router.use(newsletterRouter);
router.use(pagesRouter);
router.use(adminRouter);
router.use(adminTeamRouter);
router.use(chatRouter);
router.use(adminLeadsRouter);
router.use(storageRouter);
router.use(adminSeoRouter);
router.use(adminNewsletterRouter);
router.use(adminCmsRouter);
router.use(adminMediaRouter);
router.use(adminSettingsRouter);
router.use(adminWizardRouter);
router.use(trackingRouter);
router.use(alertsCronRouter);
router.use(adminAffiliateRouter);
router.use(adminAnalyticsRouter);
router.use(adminContentRouter);
router.use(adminSocialRouter);
router.use(adminIntegrationsRouter);

export default router;
